/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    AtudaApp: (typeof import('./src/components/icons/AtudaApp.vue'))['default']
    AutoComplete: (typeof import('./src/components/customComponents/AutoComplete.vue'))['default']
    BlueCard: (typeof import('./src/components/mainComponents/requests/requestDetails/BlueCard.vue'))['default']
    Checkbox: (typeof import('./src/components/customComponents/Checkbox.vue'))['default']
    CloseIcon: (typeof import('./src/components/icons/CloseIcon.vue'))['default']
    DateRangePicker: (typeof import('./src/components/customComponents/DateRangePicker.vue'))['default']
    DetailsIcon: (typeof import('./src/components/icons/DetailsIcon.vue'))['default']
    DownloadingUpdates: (typeof import('./src/components/icons/DownloadingUpdates.vue'))['default']
    Dropdown: (typeof import('./src/components/customComponents/Dropdown.vue'))['default']
    ErrorHandler: (typeof import('./src/components/customComponents/ErrorHandler.vue'))['default']
    FileIcon: (typeof import('./src/components/icons/FileIcon.vue'))['default']
    FileInput: (typeof import('./src/components/customComponents/FileInput.vue'))['default']
    Flow: (typeof import('./src/components/mainComponents/requests/Flow.vue'))['default']
    FlowOptions: (typeof import('./src/components/customComponents/FlowOptions.vue'))['default']
    FooterButton: (typeof import('./src/components/mainComponents/requests/FooterButton.vue'))['default']
    Home: (typeof import('./src/components/mainComponents/Home.vue'))['default']
    InfoGreyIcon: (typeof import('./src/components/icons/InfoGreyIcon.vue'))['default']
    InfoWhiteIcon: (typeof import('./src/components/icons/InfoWhiteIcon.vue'))['default']
    Loading: (typeof import('./src/components/customComponents/Loading.vue'))['default']
    Lobby: (typeof import('./src/components/mainComponents/requests/Lobby.vue'))['default']
    Login: (typeof import('./src/components/mainComponents/requests/Login.vue'))['default']
    Main: (typeof import('./src/components/mainComponents/requests/Main.vue'))['default']
    Menu: (typeof import('./src/components/customComponents/Menu.vue'))['default']
    Message: (typeof import('./src/components/mainComponents/requests/Message.vue'))['default']
    NavIcon: (typeof import('./src/components/icons/NavIcon.vue'))['default']
    Navigation: (typeof import('./src/components/mainComponents/Navigation.vue'))['default']
    OkIcon: (typeof import('./src/components/icons/OkIcon.vue'))['default']
    Popup: (typeof import('./src/components/mainComponents/requests/Popup.vue'))['default']
    RadioButtons: (typeof import('./src/components/customComponents/RadioButtons.vue'))['default']
    RadioLines: (typeof import('./src/components/customComponents/RadioLines.vue'))['default']
    RequestDetailsCard: (typeof import('./src/components/mainComponents/requests/requestDetails/RequestDetailsCard.vue'))['default']
    RequestDetailsList: (typeof import('./src/components/mainComponents/requests/requestDetails/RequestDetailsList.vue'))['default']
    RequestIcon: (typeof import('./src/components/icons/RequestIcon.vue'))['default']
    RequestList: (typeof import('./src/components/mainComponents/requests/requestCard/RequestList.vue'))['default']
    RequestSummary: (typeof import('./src/components/mainComponents/requests/requestSummary/RequestSummary.vue'))['default']
    RequestTypeCard: (typeof import('./src/components/mainComponents/requests/requestCard/RequestTypeCard.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Signature: (typeof import('./src/components/customComponents/Signature.vue'))['default']
    Stage: (typeof import('./src/components/mainComponents/requests/Stage.vue'))['default']
    StatusChip: (typeof import('./src/components/mainComponents/requests/requestDetails/StatusChip.vue'))['default']
    Textarea: (typeof import('./src/components/customComponents/Textarea.vue'))['default']
    Title: (typeof import('./src/components/mainComponents/requests/Title.vue'))['default']
    ToggleButton: (typeof import('./src/components/customComponents/ToggleButton.vue'))['default']
    UploadedFile: (typeof import('./src/components/mainComponents/requests/requestSummary/UploadedFile.vue'))['default']
    UploadIcon: (typeof import('./src/components/icons/UploadIcon.vue'))['default']
  }
}
