events {
  worker_connections  4096;  ## Default: 1024
}

http {

    server {
        listen      8081;
        charset utf-8;
        root    /usr/share/nginx/html;
        index   index.html index.htm;
        server_tokens off;
        include /etc/nginx/mime.types;

        # Always serve index.html for any request (vuejs after dist is a static page)
        location /bakashot {
            proxy_cache_bypass $http_pragma;
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options: nosniff always;
            add_header Cache-Control "no-store";
        }

        location /bakashot/assets/ {
            alias /usr/share/nginx/html/assets/;
            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options nosniff always;
            add_header Cache-Control "no-store";
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        }

        error_log  /var/log/nginx/vue-app-error.log;
        access_log /var/log/nginx/vue-app-access.log;
    }
}