name: CICD Pipeline For Development Environment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    uses: digitalidf/digitalidf-actions/.github/workflows/build-push-deploy-to-ecr.yaml@v1.3.12
    with:
      account_name: 'dev'
      image: atuda-app-client-dev
      enable_latest_tag: false
      dockerfile: Dockerfile
      build_args: |
        VITE_APP_CLIENT_ID=$VITE_APP_CLIENT_ID
        VITE_APP_AUTHORITY=$VITE_APP_AUTHORITY
        VITE_APP_REDIRECT_URL=$VITE_APP_REDIRECT_URL
        VITE_APP_NODE=$VITE_APP_NODE
        VITE_APP_TENANT_ID=$VITE_APP_TENANT_ID
      environment: development

  update-image-tag:
    needs: build-and-push
    uses: digitalidf/digitalidf-actions/.github/workflows/update-image-tag.yaml@main
    with:
      repository: 'atuda-manifests'
      path_to_deployment: 'manifests/dev/atuda-bakashot/client-deployment.yaml'
      branch_to_merge: 'master'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
